USE [master]
GO

/****** Object:  Database [DVDRental]    Script Date: 2/13/2019 11:30:15 PM ******/
CREATE DATABASE [DVDRental]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DVDRental', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQL2012\MSSQL\DATA\DVDRental.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DVDRental_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQL2012\MSSQL\DATA\DVDRental_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DVDRental] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DVDRental].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DVDRental] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DVDRental] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DVDRental] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DVDRental] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DVDRental] SET ARITHABORT OFF 
GO

ALTER DATABASE [DVDRental] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DVDRental] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [DVDRental] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DVDRental] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DVDRental] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DVDRental] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DVDRental] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DVDRental] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DVDRental] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DVDRental] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DVDRental] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DVDRental] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DVDRental] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DVDRental] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DVDRental] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DVDRental] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DVDRental] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DVDRental] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DVDRental] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DVDRental] SET  MULTI_USER 
GO

ALTER DATABASE [DVDRental] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DVDRental] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DVDRental] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DVDRental] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DVDRental] SET  READ_WRITE 
GO


